### ISSUE TITLE
Feedback on matrix-transformations

### ISSUE THREAD

**Issue by yousofy** [tbjw/ILAUBC#78] opened 2024-10-22 01:28 UTC
![image](https://github.com/user-attachments/assets/742c6736-4f87-497b-920d-85bb4f225260)
I believe this part should be "If A has m rows" instead of "If A has n rows."
I also checked with my instructor on this issue. Thanks for looking into it.

**Comment by tbjw** [comment] 2024-10-22 04:11
Thanks for the comment. I think you may have attached the wrong image,
though. Can you give a textual reference to where you think the problem is?

Thanks!
Ben Williams

**Comment by yousofy** [comment] 2024-10-22 04:14
Yee I accidentally attached the wrong Image. But then I edited it on GitHub. Since you're viewing it from email it probably didn't get updated. 

Section 4.1 under the definition of matrix transformations.

**Comment by yousofy** [comment] 2024-10-23 01:12
While you check the previous one, I noticed another typo (confirmed by my instructor again) 

![s3](https://github.com/user-attachments/assets/3a238c30-4620-43c7-978f-6f8b960d589b)

reference: https://personal.math.ubc.ca/~tbjw/ila/linear-transformations.html

I believe it should be  "columns v1, v2, ... , vn" instead of "columns v1, v2, ... , vm." 

Thanks for looking into this and the previous issue.

**Comment by yousofy** [comment] 2024-10-30 05:43
Another typo:

![image](https://github.com/user-attachments/assets/6e3a48af-ae84-481f-8b8c-5f287ceffecb)

reference (Remark under "Invertible Matrices"): https://personal.math.ubc.ca/~tbjw/ila/matrix-inverses.html

"such that AB = In and BA = Im" 

Reasoning: Because if A is n x m and B is m x n then AB produces a n x n matrix and BA produces a m x m matrix. 

Also checked with my instructor. Thanks for looking into this one too.

**Comment by tbjw** [comment] 2024-11-05 21:35
Thanks for all these. I think they should all be fixed in the next update.

**Closed** 2024-11-15 01:39 UTC
